In [10]:
import pandas as pd

In [14]:
df = pd.read_csv(r"C:\Users\juani\OneDrive\Desktop\PYTHON\myexercises\power\file.csv")
df

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86.0,4.0,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87.0,4.0,8.0,101.24,Fog
2,"1/1/2012 2:00,-1.8,-3.4,89,7,4,101.26,""Freezin...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"1/1/2012 3:00,-1.5,-3.2,88,6,4,101.27,""Freezin...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/1/2012 4:00,-1.5,-3.3,88.0,7.0,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81.0,30.0,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83.0,24.0,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93.0,28.0,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89.0,28.0,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86.0,30.0,11.3,99.89,Snow

In [15]:
df.head(10)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86.0,4.0,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87.0,4.0,8.0,101.24,Fog
2,"1/1/2012 2:00,-1.8,-3.4,89,7,4,101.26,""Freezin...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"1/1/2012 3:00,-1.5,-3.2,88,6,4,101.27,""Freezin...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/1/2012 4:00,-1.5,-3.3,88.0,7.0,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87.0,9.0,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89.0,7.0,6.4,101.29,Fog
7,1/1/2012 7:00,-1.4,-3.6,85.0,7.0,8.0,101.26,Fog
8,1/1/2012 8:00,-1.4,-3.6,85.0,9.0,8.0,101.23,Fog
9,1/1/2012 9:00,-1.3,-3.1,88.0,15.0,4.0,101.20,Fog

In [16]:
df.shape

(8784, 8)

In [17]:
df.index

RangeIndex(start=0, stop=8784, step=1)

In [19]:
df.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [21]:
df.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%           float64
Wind Speed_km/h     float64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [27]:
df['Weather'].unique()

array(['Fog', nan, 'Mostly Cloudy', 'Cloudy', 'Rain', 'Rain Showers',
       'Mainly Clear', 'Snow Showers', 'Snow', 'Clear', 'Freezing Rain',
       'Freezing Drizzle', 'Moderate Snow', 'Freezing Fog', 'Haze',
       'Drizzle', 'Thunderstorms', 'Snow Pellets'], dtype=object)

In [28]:
df.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     488
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            506
Weather               17
dtype: int64

In [29]:
df.count()

Date/Time           8784
Temp_C              8412
Dew Point Temp_C    8412
Rel Hum_%           8412
Wind Speed_km/h     8412
Visibility_km       8412
Press_kPa           8412
Weather             8412
dtype: int64

In [31]:
df['Weather'].value_counts()

Mainly Clear        2106
Mostly Cloudy       2069
Cloudy              1728
Clear               1326
Snow                 390
Rain                 306
Rain Showers         188
Fog                  150
Snow Showers          60
Drizzle               41
Haze                  16
Freezing Rain         14
Freezing Drizzle       7
Moderate Snow          4
Freezing Fog           4
Thunderstorms          2
Snow Pellets           1
Name: Weather, dtype: int64

In [32]:
Â·df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8412 non-null   float64
 2   Dew Point Temp_C  8412 non-null   float64
 3   Rel Hum_%         8412 non-null   float64
 4   Wind Speed_km/h   8412 non-null   float64
 5   Visibility_km     8412 non-null   float64
 6   Press_kPa         8412 non-null   float64
 7   Weather           8412 non-null   object
dtypes: float64(6), object(2)
memory usage: 549.1+ KB

In [33]:
df.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86.0,4.0,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87.0,4.0,8.0,101.24,Fog

In [48]:
df['Wind Speed_km/h'].nunique()

34

In [46]:
#
df['Wind Speed_km/h'].unique()

array([ 4., nan,  7.,  9., 15., 13., 20., 22., 19., 24., 30., 35., 39.,
       32., 33., 26., 44., 43., 48., 37., 28., 17., 11.,  6.,  0., 83.,
       70., 57., 46., 41., 52., 50., 63., 54.,  2.])

In [47]:
df[df['Wind Speed_km/h'] == 4]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86.0,4.0,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87.0,4.0,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79.0,4.0,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82.0,4.0,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79.0,4.0,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8766,12/31/2012 6:00,-9.7,-11.7,85.0,4.0,25.0,101.23,Cloudy
8768,12/31/2012 8:00,-8.6,-10.3,87.0,4.0,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89.0,4.0,2.4,101.09,Snow
8772,12/31/2012 12:00,-5.8,-7.5,88.0,4.0,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86.0,4.0,12.9,100.63,Snow

In [39]:
#
df.Weather.value_counts()

Mainly Clear        2106
Mostly Cloudy       2069
Cloudy              1728
Clear               1326
Snow                 390
Rain                 306
Rain Showers         188
Fog                  150
Snow Showers          60
Drizzle               41
Haze                  16
Freezing Rain         14
Freezing Drizzle       7
Moderate Snow          4
Freezing Fog           4
Thunderstorms          2
Snow Pellets           1
Name: Weather, dtype: int64

In [49]:
#
df.groupby('Weather').get_group('Rain')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
18,1/1/2012 18:00,3.8,1.0,82.0,15.0,12.9,99.74,Rain
19,1/1/2012 19:00,3.1,1.3,88.0,15.0,12.9,99.68,Rain
542,1/23/2012 14:00,2.7,-1.1,76.0,26.0,48.3,101.01,Rain
543,1/23/2012 15:00,2.7,-0.9,77.0,30.0,24.1,100.86,Rain
545,1/23/2012 17:00,3.1,-0.4,78.0,28.0,16.1,100.61,Rain
...,...,...,...,...,...,...,...,...
8537,12/21/2012 17:00,1.3,0.2,92.0,46.0,12.9,97.76,Rain
8538,12/21/2012 18:00,1.4,0.3,92.0,46.0,25.0,97.56,Rain
8539,12/21/2012 19:00,2.3,1.1,92.0,37.0,11.3,97.52,Rain
8540,12/21/2012 20:00,2.4,1.7,95.0,15.0,9.7,97.58,Rain
8541,12/21/2012 21:00,1.3,0.4,94.0,22.0,9.7,97.64,Rain

In [56]:
##########
df.isnull().sum()

Date/Time             0
Temp_C              372
Dew Point Temp_C    372
Rel Hum_%           372
Wind Speed_km/h     372
Visibility_km       372
Press_kPa           372
Weather             372
dtype: int64

In [59]:
df = df.dropna()

In [60]:
df.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [67]:
df.rename(columns = { 'Weather' : 'Weather Condition',
                      'Press_kPa' : 'kilopascal',
                      'Visibility_km' :  'Visibilitykm',
                      'Wind Speed_km/h' : 'Wind Speed',
                      'Rel Hum_%' : 'Rel Hum_%',
                      'Dew Point Temp_C%' : 'Dew Point temperature',
                      'Rel Hum_%' : 'Rel Hum_%',
                      'Temp_C' : 'Temperature',
                      'Date/Time' : 'Daytime',
                    }, inplace=False)

,Daytime,Temperature,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibilitykm,kilopascal,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86.0,4.0,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87.0,4.0,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88.0,7.0,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87.0,9.0,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89.0,7.0,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81.0,30.0,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83.0,24.0,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93.0,28.0,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89.0,28.0,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86.0,30.0,11.3,99.89,Snow

In [68]:
##########find all instances when wind speed is above 24 and visibility is 25

In [73]:
df[(df['Wind Speed'] > 24) & (df['Visibilitykm' ] == 25 )]

,Daytime,Temperature,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibilitykm,kilopascal,Weather Condition
23,1/1/2012 23:00,5.3,2.0,79.0,30.0,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77.0,35.0,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72.0,39.0,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71.0,32.0,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69.0,33.0,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76.0,26.0,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74.0,28.0,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77.0,26.0,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78.0,28.0,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77.0,26.0,25.0,101.51,Cloudy

In [74]:
df.groupby('Weather Condition').mean()

,Temperature,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibilitykm,kilopascal
Weather Condition,,,,,,
Clear,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
Fog,4.303333,3.159333,92.286667,7.946667,6.248000,101.184067
Freezing Drizzle,-5.657143,-8.000000,83.571429,16.571429,9.200000,100.202857
Freezing Fog,-7.575000,-9.250000,87.750000,4.750000,0.650000,102.320000
Freezing Rain,-3.885714,-6.078571,84.642857,19.214286,8.242857,99.647143
Haze,-0.200000,-2.975000,81.625000,10.437500,7.831250,101.482500
Mainly Clear,12.558927,4.581671,60.667142,14.144824,34.264862,101.248832
Moderate Snow,-5.525000,-7.250000,87.750000,33.750000,0.750000,100.275000
Mostly Cloudy,10.574287,3.131174,62.102465,15.813920,31.253842,101.025288
Rain,9.786275,7.042810,83.624183,19.254902,18.856536,100.233333
Rain Showers,13.722340,9.187766,75.159574,17.132979,22.816489,100.404043
Snow,-4.524103,-7.623333,79.307692,20.038462,11.171795,100.536103
Snow Pellets,0.700000,-6.400000,59.000000,35.000000,2.400000,99.700000
Snow Showers,-3.506667,-7.866667,72.350000,19.233333,20.158333,100.963500
Thunderstorms,24.150000,19.750000,77.000000,7.500000,24.550000,100.230000

In [78]:
df.groupby('Temperature').max()

,Daytime,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibilitykm,kilopascal,Weather Condition
Temperature,,,,,,,
-23.3,1/15/2012 8:00,-28.5,62.0,7.0,24.1,102.45,Clear
-23.2,1/15/2012 6:00,-28.5,62.0,7.0,25.0,102.28,Mostly Cloudy
-22.8,1/15/2012 7:00,-28.0,62.0,9.0,25.0,102.37,Mainly Clear
-22.2,1/15/2012 9:00,-27.8,60.0,9.0,48.3,102.57,Mainly Clear
-21.4,1/15/2012 2:00,-26.6,63.0,9.0,25.0,101.99,Cloudy
...,...,...,...,...,...,...,...
32.6,6/21/2012 14:00,20.4,49.0,20.0,24.1,100.25,Mainly Clear
32.7,7/14/2012 14:00,15.3,35.0,28.0,48.3,101.35,Mainly Clear
32.8,8/4/2012 15:00,18.8,44.0,17.0,24.1,101.39,Clear
32.9,7/14/2012 16:00,15.3,35.0,24.0,48.3,101.26,Mainly Clear
33.0,7/14/2012 15:00,19.0,44.0,24.0,48.3,101.31,Mainly Clear

In [77]:
df.groupby('Temperature').min()

,Daytime,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibilitykm,kilopascal,Weather Condition
Temperature,,,,,,,
-23.3,1/15/2012 8:00,-28.5,62.0,7.0,24.1,102.45,Clear
-23.2,1/15/2012 6:00,-28.5,62.0,7.0,25.0,102.28,Mostly Cloudy
-22.8,1/15/2012 7:00,-28.0,62.0,9.0,25.0,102.37,Mainly Clear
-22.2,1/15/2012 9:00,-27.8,60.0,9.0,48.3,102.57,Mainly Clear
-21.4,1/15/2012 2:00,-26.6,63.0,9.0,25.0,101.99,Cloudy
...,...,...,...,...,...,...,...
32.6,6/21/2012 14:00,20.4,49.0,20.0,24.1,100.25,Mainly Clear
32.7,7/14/2012 14:00,15.3,35.0,28.0,48.3,101.35,Mainly Clear
32.8,8/4/2012 15:00,18.8,44.0,17.0,24.1,101.39,Clear
32.9,7/14/2012 16:00,15.3,35.0,24.0,48.3,101.26,Mainly Clear
33.0,6/21/2012 15:00,16.8,38.0,22.0,24.1,100.20,Mainly Clear

In [80]:
df.groupby('Weather Condition').get_group('Fog')

,Daytime,Temperature,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibilitykm,kilopascal,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86.0,4.0,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87.0,4.0,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88.0,7.0,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87.0,9.0,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89.0,7.0,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,12/29/2012 4:00,-16.0,-17.2,90.0,6.0,9.7,101.25,Fog
8717,12/29/2012 5:00,-14.8,-15.9,91.0,4.0,6.4,101.25,Fog
8718,12/29/2012 6:00,-13.8,-15.3,88.0,4.0,9.7,101.25,Fog
8719,12/29/2012 7:00,-14.8,-16.4,88.0,7.0,8.0,101.22,Fog
8722,12/29/2012 10:00,-12.0,-13.3,90.0,7.0,6.4,101.15,Fog

In [81]:
df[(df['Weather Condition'] == 'Clear ') | (df['Visibilitykm'] > 40 )]

,Daytime,Temperature,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibilitykm,kilopascal,Weather Condition
106,1/5/2012 10:00,-6.0,-10.0,73.0,17.0,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70.0,22.0,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69.0,20.0,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66.0,26.0,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65.0,22.0,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8748,12/30/2012 12:00,-12.2,-15.7,75.0,26.0,48.3,100.91,Mostly Cloudy
8749,12/30/2012 13:00,-12.4,-16.2,73.0,37.0,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70.0,37.0,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70.0,32.0,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72.0,26.0,48.3,101.15,Mainly Clear

In [84]:
df[(df['Weather Condition'] == 'Clear ') & (df['Rel Hum_%'] > 50 ) | (df['Visibilitykm'] > 40 )]

,Daytime,Temperature,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibilitykm,kilopascal,Weather Condition
106,1/5/2012 10:00,-6.0,-10.0,73.0,17.0,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70.0,22.0,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69.0,20.0,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66.0,26.0,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65.0,22.0,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8748,12/30/2012 12:00,-12.2,-15.7,75.0,26.0,48.3,100.91,Mostly Cloudy
8749,12/30/2012 13:00,-12.4,-16.2,73.0,37.0,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70.0,37.0,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70.0,32.0,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72.0,26.0,48.3,101.15,Mainly Clear